### ISSUE TITLE
Plasmid rotation?

### ISSUE THREAD

**Issue by erinyoung** [gbouras13/dnaapler#1]
I have issues with circlator, and was hoping to use dnaapler instead. 

For plasmids, circlator uses prodigal to detect a gene somewhere in the middle and rotates the sequence to that. Does dnaapler do anything similar or does it just look for dnaA?

**Comment by gbouras13** [comment]
Hi Erin,

At the moment it doesn't. Dnaapler is a bit of just hack code I wrote really, it's not quite done!

I've had a bit of interest in dnaapler the last couple of days, so given that I am planning on making it a more usable when I get some time (bug fixes, new features, bioconda etc).

I think the best thing to do here is to implement what Ryan Wick did in Unicycler and use a repA database. Or alternatively the user can specify dnaapler choosing a random gene as you suggest. 
 
George

**Comment by gbouras13** [comment]
Hi @erinyoung ,

I'm closing this now - I've implemented such functionalities with `dnaapler plasmid` and `dnaapler mystery`.

If you have any other comments please let me know

G\orge

**Comment by erinyoung** [comment]
Thank you!
