### ISSUE TITLE
add ignore option as well as all databases option

### ISSUE THREAD

**Issue by alexweisberg** [gbouras13/dnaapler#34]
Hi, dnaapler looks great and does nearly exactly what I need for my genome assemblies.

I had a few feature requests that would make it easier to run for an entire genome.

I often have assemblies with chromosomes and plasmids and would like to rotate all of them simultaneously, rather than running it for the chromosome and the plasmids separately. I could make a custom db with dnaA and repA and run with bulk, but it would be convenient to have an 'all' option that rotates all chromosomes and plasmids in a fasta file.

My second request is tied to this first one. I work with _Agrobacterium_, which has a circular chromosome and a second linear chromosome. I would like to rotate the circular chromosome but not the linear one. Similarly, sometimes I have nearly complete assemblies where the chromosome is almost but not quite complete, and the plasmids are complete. I would like to rotate only the contigs that are assembled as circular molecules. 
The easiest way to get around this would be to have an 'ignore' option like circlator's that would let me provide a list of contigs to ignore.

Thanks!

-Alex

**Comment by gbouras13** [comment]
Hi @alexweisberg,

Thanks for the great suggestions - they shouldn’t be too hard to implement.

George

**Comment by gbouras13** [comment]
The other thing I will implement with `all` is to prefer hits for dnaA over terL if both are found - in my limited testing so far, I've had instances where the chromosome had a better hit for terL (prophage) than dnaA. RepA and terL clashes would likely be phage-plasmids and I'm not sure which one to prefer in that case!

George

**Comment by alexweisberg** [comment]
Hi George,

Thank you for looking into these!
Yes, I think the best output would be to have a single Fasta file with all contigs regardless of whether they were rotated. The tsv file would be nice as well. I am not sure what your default is but maybe adjust the contig name of rotated contigs to include _rotated or something similar?

I agree that preferring dnaA would be preferable over terL. Personally I would prefer repA over terL but I could see how others may differ!

Best,
Alex

**Comment by gbouras13** [comment]
Hi @alexweisberg,

I've incorporated most of these changes into `dnaapler all` - into the main branch and available from a source install.

If you have a chance, would you mind giving it a go?

I'll push a release to pypi and conda afterwards :)

George

**Comment by gbouras13** [comment]
No problems at all Alex, thanks again for the great suggestions!

George

**Comment by alexweisberg** [comment]
I just remembered as well, based on the printed output, it appears that the 'all' option, which relies on the bulk fasta validation, requires more than one sequence in the input fasta file. Given that I am often running this for many strains, it would be nice if this was relaxed to allow for annotating 'all' even if there is just one sequence, such as a single chromosome or plasmid. 

Thanks!

**Comment by alexweisberg** [comment]
Hi George,

Great! Thank you again for adding this feature so quickly, it is really useful for our analyses and I have it running on 96 genomes as we speak.

Best,
Alex

**Comment by gbouras13** [comment]
For anyone reading this in future, these changes have been released in v0.3.0.
