### ISSUE TITLE
Improve autocomplete

### ISSUE THREAD

**Issue by simone-pignotti** [gbouras13/dnaapler#44]
Hi @gbouras13, I have encountered a case where there are multiple blast hits with very low evalue (1e-180) that just happened to miss the start of the target by few residues, so they were discarded and a random gene ("nearest" option) was used instead.
I think that in those cases it would be best to use the ORF that overlaps the best blast hit, and even make this the default when `--autocomplete` is not specified. What do you think?

**Comment by simone-pignotti** [comment]
At least that's my interpretation based on:
https://github.com/gbouras13/dnaapler/blob/6a672fdd2f60a6cdbf9b6c4faf30432dbaa27653/src/dnaapler/utils/processing.py#L78-L82
But correct me if I am wrong, I can take a closer look at the logs

**Comment by gbouras13** [comment]
I chose to have a strict match of the start codon in dnaapler to ensure the rotation does not interrupt a CDS, but I agree this would be a good feature.

I will aim to add this in the next week or two. It will require some refactoring and so isn't trivial but shouldn't be too hard.

George

**Comment by gbouras13** [comment]
Hi @simone-pignotti ,

I've made your suggestion the default within all BLAST based commands in dnaapler (aka it will take the top row of the blastx table, and if it the matching alignment doesn't start with a start codon, it will run pyrodigal to find the CDS with the most overlap).

Available in v0.4.0

George

**Comment by simone-pignotti** [comment]
Wonderful, thank you so much @gbouras13!
