### ISSUE TITLE
[JOSS Review] Typos in CONTRIBUTING.md

### ISSUE THREAD

**Issue by mkerin** [gbouras13/dnaapler#49]
Re [joss-reviews/issues/5968](https://github.com/openjournals/joss-reviews/issues/5968)

Hi @gbouras13,

There are a couple of places in the CONTRIBUTING.md file which reference one of your other projects (`phrokka`) rather than `dnaapler`. Could you please take a look and make sure that the contribution guidelines are appropriate for this repo? It might also be nice to link them in the main README.md.

**Comment by gbouras13** [comment]
Thanks @mkerin ,

This has been addressed in #54 and #55. I will also included a link to the README.md in a later PR.

**Comment by mkerin** [comment]
Thank you for taking a look at this - I agree that the issue is resolved. Closing now.
