### ISSUE TITLE
[JOSS Review] Authorship list

### ISSUE THREAD

**Issue by mkerin** [gbouras13/dnaapler#50]
Re [joss-reviews/issues/5968](https://github.com/openjournals/joss-reviews/issues/5968)

Hi @gbouras13 

I have a question about the list of authors in the JOSS paper. I can see that 3/5 of the authors have made contributions to the repo, but I am unclear about the contributions of the remaining authors. Could you please clarify what their contribution was?

I note that I've seen some JOSS papers provide a statement of author contributions according to the [Credit](https://beta.elsevier.com/researcher/author/policies-and-guidelines/credit-author-statement) guidelines, but this doesn't appear to be required.

**Comment by gbouras13** [comment]
Hi @mkerin ,

I'm not sure how to include this (or if it needs to be) for the manuscript but I will outline here:

GB: conceptualisation, methodology, software, validation, writing - original draft, writing - editing and review

SRG: validation, writing - editing and review

BP: methodology, validation, writing - editing and review

VM: software, writing - editing and review, visualisation, supervision

MJR: software, writing - editing and review, supervision

**Comment by mkerin** [comment]
Thank you - this is sufficient. Closing now.
