### ISSUE TITLE
Add option to annotate fasta headers with Gene_Reoriented

### ISSUE THREAD

**Issue by ammaraziz** [gbouras13/dnaapler#67]
Thanks for creating and maintaining dnaapler! It's running fantastically well. I had a feature request:

**Is your feature request related to a problem? Please describe.**
I am running `dnaapler all ...` as the input contains both plasmids and genomes.

 `dnaapler` outputs fasta headers in the format `{contig_name} rotated=True`. I want to know which gene (dnaA, repA, etc) was used to reorientate which sequence. 

**Describe the solution you'd like**
The information is captured as it's present in `*_summary.tsv` file. Fingers crossed this isn't a big ask

**Describe alternatives you've considered**
NA

**Additional context**
NA

Thanks!

**Comment by gbouras13** [comment]
Fixed by v0.5.1 thanks for suggesting this @ammaraziz

**Comment by ammaraziz** [comment]
Thank you @gbouras13 ! Very helpful
