### ISSUE TITLE
Add archaea support

### ISSUE THREAD

**Issue by gbouras13** [gbouras13/dnaapler#75]
https://github.com/gbouras13/hybracter/issues/81

**Comment by richardstoeckl** [comment]
I think this is the appropriate place to add some discussion for the archaea support. - first of all thank you so much for taking this into consideration!

Again for documentation:
Since the NCBI COGs database lists [DnaA as basically nonexistent in most archaea](https://www.ncbi.nlm.nih.gov/research/cog/cog/COG0593/), this gene is obviously not a good candidate for archaea.
Unfortunately, there were no real answers [from the community what to use instead](https://x.com/GB13Faithless/status/1802307545564061750).

However, I will be attending the [Molecular biology of Archaea](https://meetings.embo.org/event/24-archaea) conference next week, where I certainly will be asking the archaeal genome experts there for some input, so I can offer to share this feedback with you :)

**Comment by richardstoeckl** [comment]
Hi,

talking to the some people at the Molecular Archaea conference, I quickly realized that the most 1-to-1 equivalent to using DnaA in Archaea would probably be using Orc1/cdc6, as it is [found in almost all archaea](https://www.ncbi.nlm.nih.gov/research/cog/cog/COG1474/). Specifically, Orc1-1 might be the best solution, as it is is usually found right next to the Ori 1.

Best,
Richard

**Comment by gbouras13** [comment]
@richardstoeckl,

This is awesome thanks. Do you know if bacteria also have this (looks not commonly based on your link?)

If not, then I'll add this into `dnaapler all` as well as creating a subcommand `dnaapler archaea` which I will do regardless

George

**Comment by richardstoeckl** [comment]
No, to my knowledge the Orc1/cdc6 family of proteins is not really used in bacteria ([see  e.g. Fig. 1 of Raymann et al. 2014: "Global Phylogenomic Analysis Disentangles the Complex Evolutionary History of DNA Replication in Archaea"](https://academic.oup.com/gbe/article/6/1/192/666907#89445653)).

One problem I can foresee with using Orc1/cdc: the archaeal order _Methanococcales_ were thought to **lack homologs entirely**, and some members of the Family _Halobacteriaceae_ posess **large number of extra copies** ([see  e.g. Fig. 2 of Raymann et al. 2014](https://academic.oup.com/gbe/article/6/1/192/666907#89445653), and [Bell, S.D., 2012: "Archaeal orc1/cdc6 proteins. The Eukaryotic Replisome: a Guide to Protein Structure and Function", pp.59-69.](https://link.springer.com/chapter/10.1007/978-94-007-4572-8_4)).

However, [Kira S. Makarova and Eugene V. Koonin (2013)](https://cshperspectives.cshlp.org/content/5/11/a012963.full) show that there seem to be two major groups of ORC proteins, "[...] namely, the slow-evolving arORC1 and the fast-evolving arORC2 [...]", and they also suggest "[...] a subfamily of archaeal AAA+ ATPases (arCOG00472) that are fused to the carboxy-terminal wHTH domain and clusters with the arORC2 branch in the phylogenetic tree [...]", so maybe **using the [arCOG HMMs](https://ftp.ncbi.nlm.nih.gov/pub/wolf/COGs/arCOG/) arCOG00467, arCOG00468, arCOG00471, and arCOG00471** would get the desired results?

**Comment by gbouras13** [comment]
Hi @richardstoeckl ,

thanks so much mate - When I get to implementing this I’ll do some benchmarks to make sure they don’t affect the reorientation of bacterial genomes (my feeling is it won’t but we will see!).

George

**Comment by gbouras13** [comment]
Hi @richardstoeckl ,

I'm looking at this now. After some reading, I think adding too many genes is bad (as it is likely to lead some reorientation inconsistencies if multiple genes are found in a certain archaeon). 

As this is a pretty niche case (sorry archaea people!) and I have limited development time at the moment, I don't want to spend too much time coding it up to account for multiple homologous gene hits and more complications. 

Therefore, I think that I will add support for Orc1/cdc6 only. If you are reorienting other archaea without this gene, I'd recommending using a custom database with dnaapler.

George

**Comment by gbouras13** [comment]
I think just using 'COG1474' ends up being your solution anyway @richardstoeckl . So I am going to use all proteins from here https://ftp.ncbi.nlm.nih.gov/pub/wolf/COGs/arCOG/ that are COG1474.

George
