### ISSUE TITLE
Option to ignore errors linked to genome

### ISSUE THREAD

**Issue by jsgounot** [gbouras13/dnaapler#76]
**Is your feature request related to a problem? Please describe.**
When we add dnaapler in a pipeline, it's hard to distinguish if dnaapler fails because some sequences have issues (e.g. 0 blast hit) or if there is a fatal error (unable to run the program). We don't want the whole process to fail because dnaapler is unable to make its magic on one or some contigs.

**Describe the solution you'd like**
While it might not be the recommended way for punctual use, it would be nice to have an option that ignores this kind of error, and the contigs affected would just return as they were in the input, so we can continue processing the data.

**Comment by jsgounot** [comment]
One of the simple changes could be to replace the current `logger.error` to `logger.warning` such as [this one](https://github.com/gbouras13/dnaapler/blob/ea07689c37af5e27134691b28f909ac3b59a400e/src/dnaapler/utils/all.py#L69_).

**Comment by gbouras13** [comment]
Hi @jsgounot ,

Agreed and this will be an easy request. I’m a bit short on software maintenance/improvement time right now but will get to it in a few weeks probably.

George

**Comment by jsgounot** [comment]
Coll thanks!

**Comment by KR0manova** [comment]
Seconding this request, would be fantastic! Thank you for this tool.

**Comment by gbouras13** [comment]
Hi @jsgounot ,

I've implemented a fix for this (looks like #74 had the same bug/request). So in the next version once released, if you have no BLAST hits and specified `-a none`, then dnaapler will behave as you wish.

George

**Comment by jsgounot** [comment]
Ok, I'll wait for the release then. Thanks.

**Comment by gbouras13** [comment]
available in v0.8.0
